#!/usr/bin/env bash
## groot Install
# Install script for groot
# install script
# Source Code produced by Willtech 2026
# v1.1 hand coded by HRjJ

CompletedMessage="Usage: groot {filespec}"

if [ `whoami` != root ]; then
    echo Please run as sudo user
    exit
fi

cp ./groot /usr/bin/groot
chmod +x /usr/bin/groot

echo -e ${CompletedMessage}
